### ISSUE TITLE
[BUG]: The Obsessive Shadow is waaayyy too sexy.

### ISSUE THREAD

**Issue by ThatMegalosaurus** [Sleepy-Dog-Studios/Bug-Reports#7]
### Game Name

- [X] The Obsessive Shadow
- [ ] OliVR
- [ ] Other

### Describe the Bug

Everytime I look at him, ohhhh man.

### How do we reproduce the bug?

1. Put on your VR headset
2. Look through it
3. open your eyes
4. keep breathing (I know its hard, but you can do it)
5. see him
6. see the sexy man
7. have a heart attack
8. hospital
9. in debt because of the hospital
10. I hate the American health care system
11. repeat.

### What is the expected behavior?

he just kept staring, with those sexy, sexy eyes.

### Screenshots (if applicable)

![image](https://user-images.githubusercontent.com/129015350/227813979-5024ae7e-b375-4f21-a69e-c4a38ca68e8e.png)
![image (1)](https://user-images.githubusercontent.com/129015350/227814049-a8b068a7-d249-4cdb-bcc3-52830b28751f.png)

### What device are you playing on?

Other

### What is the version you are playing on?

My eyeballs

### Icon request checklist

- [X] I agree that this bug report is true and honest.
- [X] I agree that I created this bug report with as much detail as possible.
- [X] I am going to have an amazing rest of my day!

**Comment by DylanDevelops** [comment]
Haha, we are glad that the gameplay experience is good but try to keep these reports specific to if there are real bugs we need to fix!

**Comment by ThatMegalosaurus** [comment]
A real disappointment..
