### ISSUE TITLE
[BUG]: cant see my hands and shaking camera pcvr

### ISSUE THREAD

**Issue by Syoboncat** [Sleepy-Dog-Studios/Bug-Reports#8]
### Game Name

- [X] The Obsessive Shadow
- [ ] OliVR
- [ ] Other

### Describe the Bug

I cant see me hands and the camera is shaking pcvr.it makes it unplayable because i cant see my hands.if i cant see my hands i cant press play that means they are not tracked (in main menu)

### How do we reproduce the bug?

1.put on ur headset
2.turn on the game
3.and thats all

### What is the expected behavior?

I expected to happen that everything will be not glitched

### What device are you playing on?

Other

### What is the version you are playing on?

0.0.6

### Icon request checklist

- [X] I agree that this bug report is true and honest.
- [X] I agree that I created this bug report with as much detail as possible.
- [X] I am going to have an amazing rest of my day!

**Comment by DylanDevelops** [comment]
Fixed in 0.0.6b. Thank you so much for your bug report and for making our game better!

- Dylan R
